name = "Mercy Modpack"
author = "Khorne & Mercy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "33ea12614b07b9a1ee098f3718f215c59ddb7bf907ce56cd48c9ebf4d7308ea0"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
