name = "Mercy Modpack"
author = "Khorne & Mercy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "402e2f861f76066f3efd6a6ca0f87be50e14bbb1c2c91ade5757a50f21f172ab"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
