name = "Mercy Modpack"
author = "Khorne & Mercy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fa30aebb14f015d87d0af0b019eda0fdd5eda1af97903efccc2972d1fa7a726"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
